runtime: python
env: flex
automatic_scaling:
  cool_down_period_sec: 120
  min_num_instances: 1
  max_num_instances: 15
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 10
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 20